## Default profile
spring:
  application:
    name: emuda
  profiles:
    group:
      "local": "local, jwt, oauth-local"
      "dev": "dev, jwt, oauth-dev"
    active: dev
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  use-fqn: true
---
# Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/edupackdb
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MariaDB53Dialect
---
# Dev Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/edupackdb
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

logging:
  level.org:
      hibernate.SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
